# Generated by Django 2.2.2 on 2019-12-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(db_column='CI', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('apellido', models.CharField(db_column='Apellido', max_length=30)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('edad', models.IntegerField(db_column='Edad')),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='persona.Persona')),
                ('cod_tlf', models.AutoField(db_column='Cod_Tlf', primary_key=True, serialize=False)),
                ('cod_area1', models.PositiveIntegerField(db_column='Cod_Area1')),
                ('cod_area2', models.PositiveIntegerField(blank=True, db_column='Cod_Area2', null=True)),
                ('num1', models.IntegerField(db_column='Num1')),
                ('num2', models.IntegerField(blank=True, db_column='Num2', null=True)),
                ('ci_related', models.ForeignKey(db_column='CI', on_delete=django.db.models.deletion.CASCADE, related_name='ci_linked', to='persona.Persona')),
            ],
            options={
                'db_table': 'telefono',
                'managed': True,
            },
            bases=('persona.persona',),
        ),
    ]
