# Generated by Django 2.2.2 on 2019-12-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioTieneTratamiento',
            fields=[
                ('cod_servicio', models.ForeignKey(db_column='Cod_Servicio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='treatment.Servicio')),
            ],
            options={
                'db_table': 'servicio_tiene_tratamiento',
                'managed': False,
            },
        ),
    ]
