# Generated by Django 2.2.2 on 2019-12-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('date', '0001_initial'),
        ('debtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('cod_pago', models.AutoField(db_column='Cod_Pago', primary_key=True, serialize=False)),
                ('monto', models.FloatField(db_column='Monto')),
                ('inicial', models.FloatField(blank=True, db_column='Inicial', null=True)),
                ('cuota1', models.FloatField(blank=True, db_column='Cuota1', null=True)),
                ('cuota2', models.FloatField(blank=True, db_column='Cuota2', null=True)),
                ('tipo_pago', models.CharField(db_column='Tipo_Pago', max_length=8)),
                ('metodo_pago', models.CharField(db_column='Metodo_Pago', max_length=10)),
                ('num_ref', models.IntegerField(blank=True, db_column='Num_Ref', null=True)),
                ('cod_fecha', models.ForeignKey(blank=True, db_column='Cod_Fecha', null=True, on_delete=django.db.models.deletion.CASCADE, to='date.Fecha', unique=True)),
                ('cod_moroso', models.ForeignKey(blank=True, db_column='Cod_Moroso', null=True, on_delete=django.db.models.deletion.CASCADE, to='debtors.Moroso', unique=True)),
                ('cod_paciente', models.ForeignKey(blank=True, db_column='Cod_Paciente', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Paciente', unique=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('cod_recibo', models.AutoField(db_column='Cod_Recibo', primary_key=True, serialize=False)),
                ('num_pago', models.IntegerField(blank=True, db_column='Num_Pago', null=True)),
                ('cod_paciente', models.ForeignKey(db_column='Cod_Paciente', on_delete=django.db.models.deletion.CASCADE, to='patients.Paciente', unique=True)),
                ('cod_pago', models.ForeignKey(blank=True, db_column='Cod_Pago', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Pago', unique=True)),
            ],
            options={
                'db_table': 'recibo',
                'managed': True,
            },
        ),
    ]
