# Generated by Django 2.2.2 on 2019-12-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitasAsistidas',
        ),
        migrations.DeleteModel(
            name='CitasAusentes',
        ),
        migrations.DeleteModel(
            name='CitasCanceladas',
        ),
    ]
