# Generated by Django 2.2.2 on 2019-12-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteSolicitaServicio',
            fields=[
                ('cod_paciente', models.ForeignKey(db_column='Cod_Paciente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.Paciente')),
            ],
            options={
                'db_table': 'paciente_solicita_servicio',
                'managed': False,
            },
        ),
    ]
