# Generated by Django 2.2.2 on 2019-12-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moroso',
            fields=[
                ('cod_moroso', models.AutoField(db_column='Cod_Moroso', primary_key=True, serialize=False)),
                ('saldo_deudor', models.FloatField(blank=True, db_column='Saldo_Deudor', null=True)),
                ('fecha_limite', models.DateField(blank=True, db_column='Fecha_Limite', null=True)),
                ('fecha_ultimo_pago', models.DateField(blank=True, db_column='Fecha_Ultimo_Pago', null=True)),
                ('cod_fecha', models.ForeignKey(blank=True, db_column='Cod_Fecha', null=True, on_delete=django.db.models.deletion.CASCADE, to='date.Fecha', unique=True)),
                ('cod_paciente', models.ForeignKey(db_column='Cod_Paciente', on_delete=django.db.models.deletion.CASCADE, to='patients.Paciente', unique=True)),
            ],
            options={
                'db_table': 'moroso',
                'managed': True,
            },
        ),
    ]
