# Generated by Django 2.2.2 on 2019-12-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('cod_fecha', models.AutoField(db_column='Cod_Fecha', primary_key=True, serialize=False)),
                ('fecha_f', models.DateField(db_column='Fecha_F')),
            ],
            options={
                'db_table': 'fecha',
                'managed': True,
            },
        ),
    ]
